export const invoiceStatuses = {
  initial: 1,
  paid: 2,
  receipt_attach: 3,
}
export const entityTypes = {
  personal: 1,
  corporate: 2,
  governorate: 3,
}
export const identityTypes = {
  nationalID: 1,
  passportNo: 2,
  electionID: 3,
}
export const QUERY_KEY = {
  user: 'USER',
  branches: 'BRANCHES',
  cities: 'CITIES',
  nationalities: 'NATIONALITIES',
  clientTypes: 'CLIENT_TYPES',
  genders: 'GENDERS',
  imageType: 'IMAGE_TYPE',
  'SEARCH-CLIENT-BRANCHES': 'SEARCH-CLIENT-BRANCHES',
  'SEARCH-CLIENT-NATIONALITIES': 'SEARCH-CLIENT-NATIONALITIES',
  'ADDTIMESHEET-EMPLOYEES': 'ADDTIMESHEET-EMPLOYEES',
  'ADDTIMESHEET-TASKTYPES': 'ADDTIMESHEET-TASKTYPES',
  'ADDTIMESHEET-TASKSTATUS': 'ADDTIMESHEET-TASKSTATUS',

  'ADDFILE-CASESNUMBER': 'ADDFILE-CASESNUMBER',
  'ADDFILE-HEARINGTYPES': 'ADDFILE-HEARINGTYPES',
  'ADDFILE-CONSULTANTS': 'ADDFILE-CONSULTANTS',
  'ADDFILE-LAWYERS': 'ADDFILE-LAWYERS',
  'ADDFILE-ADMINS': 'ADDFILE-ADMINS',
  'ADDFILE-SECRETARYLIST': 'ADDFILE-SECRETARYLIST',
  'ADDFILE-HEARINGS': 'ADDFILE-HEARINGS',
  'ADDFILE-EDITABLEHEARING': 'ADDFILE-EDITABLEHEARING',
  'ADDFILE-EDITABLESTAGE': 'ADDFILE-EDITABLESTAGE',
  'ADDFILE-STAGES': 'ADDFILE-STAGES',
  'ADDFILE-DOCUMENTs': 'ADDFILE-DOCUMENTs',
  'ADDFILE-EDITDOCUMENT': 'ADDFILE-EDITDOCUMENT',
  'CASEREPORTS-COURT': 'CASEREPORTS-COURT',
  'CASEREPORTS-CASETYPE': 'CASEREPORTS-CASETYPE',
  'CASEREPORTS-COLUMNS': 'CASEREPORTS-COLUMNS',
  'GET-ALL-LOOKUPS': 'GET-ALL-LOOKUPS',
}
